version: '3.8'

services:
  service-a:
    image: myrepo/service-a:latest
    ports:
      - "5001:5000"
    environment:
      - SERVICE_NAME=Service A

  service-b:
    image: myrepo/service-b:latest
    ports:
      - "5002:5000"
    environment:
      - SERVICE_NAME=Service B

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
